apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    annotations:
      olm.providedAPIs: ""
    name: openshift-storage-gcg6m
    namespace: openshift-storage
  spec:
    targetNamespaces:
    - openshift-storage
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
