# Alternative:
# oc patch console.operator cluster -n openshift-storage --type json -p '[{"op": "add", "path": "/spec/plugins", "value": ["odf-console"]}]'

apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: odf-console
spec:
  displayName: ODF Plugin
  service:
    basePath: /
    name: odf-console-service
    namespace: openshift-storage
    port: 9001
