---
# tasks file for roles

- name: Restore a backup
  tags:
    - restoreBackup
  k8s:
    state: present
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
    definition: "{{ lookup('template', 'postgres-restore.yaml.j2') }}"


